#!/bin/sh

HOSTNAME=`hostname`

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#9DBEA0ee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

BL='#000000cc'  # smoky black
WT='#ffffffff'  # white
DB='#575757cc'  # smoky dark gray


i3lock \
--insidevercolor=$C   \
--ringvercolor=$B     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$DB      \
--ringcolor=$BL        \
--linecolor=$B        \
--separatorcolor=$B   \
\
--verifcolor=$B        \
--wrongcolor=$W        \
--timecolor=$WT        \
--datecolor=$WT        \
--layoutcolor=$T      \
--keyhlcolor=$WT       \
--bshlcolor=$W        \
\
-i ~/.config/i3/image/lockscreen_$HOSTNAME.png \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y"

#--blur 5              \
# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc